import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copy } from 'esbuild-plugin-copy';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const commonConfig = {
	banner: {
		js: banner,
	},
	bundle: true,
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	plugins: [
		copy({
			assets: [
				// No extra assets required for JIT embedding + rerank flow.
			],
		}),
	],
};

// Plugin to mock Node.js built-ins for the worker
const ignorePlugin = {
	name: 'ignore-node-modules',
	setup(build) {
		// Mock nodejieba specifically to return null so checking if (jieba) fails gracefully
		build.onResolve({ filter: /^nodejieba$/ }, args => {
			return { path: args.path, namespace: 'ignore-nodejieba' };
		});

		build.onLoad({ filter: /.*/, namespace: 'ignore-nodejieba' }, args => {
			return { contents: 'throw new Error("nodejieba disabled in browser build");' };
		});

		// Mock standard Node.js built-ins
		build.onResolve({ filter: /^(fs|url|crypto|os|tty|util|net|http|https|zlib|stream|events|assert|child_process|cluster|dgram|dns|domain|punycode|querystring|readline|repl|string_decoder|tls|v8|vm|module|constants|timers|console|process)$/ }, args => {
			return { path: args.path, namespace: 'ignore-node-modules' };
		});

		build.onLoad({ filter: /.*/, namespace: 'ignore-node-modules' }, args => {
			return { contents: 'module.exports = {};' };
		});
	},
};

const workerBuildOptions = {
	...commonConfig,
	entryPoints: ["src/worker/worker.ts"],
	platform: "browser",
	format: "iife",
	outdir: "dist-inline-worker",
	write: false,
	metafile: true,
	define: {
		"process.versions.node": "undefined",
		"import.meta.url": JSON.stringify("file://")
	},
	alias: {
		"path": "path-browserify"
	},
	plugins: [
		...commonConfig.plugins,
		ignorePlugin
	],
	external: [
		"obsidian",
	],
};

const inlineWorkerPlugin = {
	name: "inline-worker",
	setup(build) {
		build.onResolve({ filter: /^virtual:worker$/ }, () => {
			return { path: "virtual:worker", namespace: "inline-worker" };
		});

		build.onLoad({ filter: /.*/, namespace: "inline-worker" }, async () => {
			const result = await esbuild.build(workerBuildOptions);
			const output = result.outputFiles[0].text;
			const watchFiles = result.metafile ? Object.keys(result.metafile.inputs) : [];
			return {
				contents: `export default ${JSON.stringify(output)};`,
				loader: "js",
				watchFiles
			};
		});
	},
};

const mainContext = await esbuild.context({
	...commonConfig,
	entryPoints: ["main.ts"],
	outfile: "main.js",
	plugins: [
		...commonConfig.plugins,
		inlineWorkerPlugin,
	],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
});

if (prod) {
	await mainContext.rebuild();
	process.exit(0);
} else {
	await mainContext.watch();
}
